"""update_userrole_enum_to_lowercase_labels

Revision ID: 692071db2a36
Revises: <PREVIOUS_REVISION_ID_IF_ANY> 
Create Date: <TIMESTAMP>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from app.models import UserRole # Adjust path as necessary if you need to import the Python Enum for reference

# revision identifiers, used by Alembic.
revision: str = '692071db2a36'
down_revision: Union[str, None] = None # placeholder, to be filled by user
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define the ENUM type name and its old/new labels
USER_ROLE_ENUM_NAME = 'userrole'
NEW_LABELS = ['author', 'editor', 'referee', 'admin']
# Assuming your old labels were uppercase. Adjust if they were different.
OLD_LABELS = ['AUTHOR', 'EDITOR', 'REFEREE', 'ADMIN']

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute(f"ALTER TYPE {USER_ROLE_ENUM_NAME} RENAME TO {USER_ROLE_ENUM_NAME}_old;")
    
    op.execute(f"CREATE TYPE {USER_ROLE_ENUM_NAME} AS ENUM({', '.join(repr(label) for label in NEW_LABELS)});")

    # Update the 'users' table
    op.execute(
        f"ALTER TABLE users ALTER COLUMN role TYPE {USER_ROLE_ENUM_NAME} "
        f"USING role::text::{USER_ROLE_ENUM_NAME};"
    )
    
    # Update the 'journalentryprogress' table
    op.execute(
        f"ALTER TABLE journalentryprogress ALTER COLUMN owner_role TYPE {USER_ROLE_ENUM_NAME} "
        f"USING owner_role::text::{USER_ROLE_ENUM_NAME};"
    )

    op.execute(f"DROP TYPE {USER_ROLE_ENUM_NAME}_old;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(f"ALTER TYPE {USER_ROLE_ENUM_NAME} RENAME TO {USER_ROLE_ENUM_NAME}_new;")

    op.execute(f"CREATE TYPE {USER_ROLE_ENUM_NAME} AS ENUM({', '.join(repr(label) for label in OLD_LABELS)});")

    # Update the 'users' table
    op.execute(
        f"ALTER TABLE users ALTER COLUMN role TYPE {USER_ROLE_ENUM_NAME} "
        f"USING role::text::{USER_ROLE_ENUM_NAME};"
    )

    # Update the 'journalentryprogress' table
    op.execute(
        f"ALTER TABLE journalentryprogress ALTER COLUMN owner_role TYPE {USER_ROLE_ENUM_NAME} "
        f"USING owner_role::text::{USER_ROLE_ENUM_NAME};"
    )

    op.execute(f"DROP TYPE {USER_ROLE_ENUM_NAME}_new;")

    # ### end Alembic commands ### 